### ISSUE TITLE
Custom Fields availability

### ISSUE THREAD

**Issue by b-A-shi** [at-gmbh/personio-py#21]
Hey,
first of all thank you for this Libary it helps me a lot in my Daily work.

I want to ask if there is a possibility to receive Custom fields from Personio via the Library? 
There are around 10 different fields in our Personio which i cant access right now.

I thought about a function in the Library to add them by myself cause these fields different from instance to instance.

**Comment by klamann** [comment]
sure, you can access custom fields with personio-py. They can all be found under the `dynamic` property of your `Employee` objects.

If your custom fields are not in this dictionary, maybe you need to configure access to those fields in the Personio settings.

You can also define a mapping for custom fields that have other types than strings using the `DynamicMapping` class. There is [an example in the test cases](https://github.com/at-gmbh/personio-py/blob/a4c8a5b3dd09d82654f3081b8c29167a25f6d253/tests/test_employee.py#L67).

**Comment by b-A-shi** [comment]
got it, thank you!
I would love to see an update on the User guide :D
